namespace Axpense.Infrastructure.Intertfaces
{
    /// <summary>
    /// Provider-agnostic file storage. Keys are opaque, tenant-prefixed paths generated by the
    /// storage itself; callers persist the key and never build paths on their own.
    /// Swap the implementation (local disk → S3/Azure Blob) without touching business modules.
    /// </summary>
    public interface IFileStorage
    {
        Task<string> SaveAsync(Guid organizationId, string folder, Stream content, string extension, CancellationToken cancellationToken = default);
        Task<Stream?> OpenReadAsync(string key, CancellationToken cancellationToken = default);
        Task DeleteAsync(string key, CancellationToken cancellationToken = default);
        /// <summary>Total bytes stored for an organization (subscription storage meter).</summary>
        Task<long> UsageBytesAsync(Guid organizationId, CancellationToken cancellationToken = default);
    }
}
